# Class 1 Multilingualism Poland 

The course is in Moodle <- course 5606 MaFLA 
Password: MW_2021

Three lectures are obligatory for this course:

First is Ellen Bialystock - 10/21 at 5:00pm Polish time 

10/19 no class - two weeks from today. 

11/18, means no class 

Simone Pfenniger - good analysis according to Wrembel. 
U Salzburg 

## What is multilingualism? 

- The use of languages in a culuture or in an individual?

- Is bilingualism multilingualism? 

- Terminology
 - L1, L2, L3/Ln 
 - Classifications: chronology or dominance? 
 - Heritage speakers and L1: 2 L1's?
 
 - Route of acquisition
  - L1, L2, L3, Ln simultaneously
  - L1 -> L2 -> L3 -> Ln successively 
  - L1, L2 -> L3 mixed 
  - L1 -> L2, L3 mixed 
  
# Types of bi-/multilingualism 

Additive - L2 is cool
Subractive - L2 is not cool and hurts L1 
Simultaneous 
Successive
Early bilingualism
Late bilinguamism 
Balanced bilingualism 
Dominant language 
Bilinguals from birth
immersion programs/learners at school
migrants
regional/ethnic minorities 
sign language users 
others...
A continuum

# Classifying bilinguals 

- Language status
- Currently level of L2 fluency
- L1-L2 language competence 
- AoA 
- L2 on L1 influence 
- Context/manner of acquisition
- Typology of languages 
- language prestige 
- frequency/recency of use 
- control ability
- switching habits 
  
  
# Reading
  
  B. Berthele (2021)2
 